ALTER TABLE samples
  ADD COLUMN IF NOT EXISTS dns_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS connect_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tls_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ttfb_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS download_ms DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tls_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS assertion_failures_jsonb JSONB;
